# Generated by Django 6.0.6 on 2026-06-19 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon_path', models.CharField(blank=True, max_length=200)),
                ('icon_file', models.FileField(blank=True, null=True, upload_to='module_icons/')),
                ('is_external', models.BooleanField(default=False, help_text='Check if this module links to an external system or API.')),
                ('base_url', models.URLField(blank=True, help_text="Base URL for this module's external API.", null=True)),
                ('redirect_url', models.URLField(blank=True, help_text='Final landing page after successful login (optional).', null=True)),
                ('external_api_url', models.URLField(blank=True, help_text="API endpoint for external module login (used if 'is_external' is True).", null=True)),
                ('url_name', models.CharField(blank=True, help_text='Django named URL for internal navigation.', max_length=200)),
                ('show_in_home', models.BooleanField(default=True, help_text='Show this module in the home page menu.')),
                ('is_active', models.BooleanField(default=True, help_text='Is this module currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppModuleAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='userspermissionsystem.appmodule')),
            ],
            options={
                'verbose_name_plural': 'App module aliases',
            },
        ),
        migrations.CreateModel(
            name='AppURLPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='userspermissionsystem.appmodule')),
            ],
            options={
                'unique_together': {('app', 'url', 'method', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Programmatic role key. Auto-filled from name when empty.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='userspermissionsystem.appurlpermission')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='users', to='userspermissionsystem.appurlpermission')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='userspermissionsystem.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSyncEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('create', 'User Create'), ('password', 'Password Change'), ('status', 'Status Change'), ('update', 'User Update'), ('access', 'Access/Permission Sync')], max_length=50)),
                ('platform_type', models.CharField(choices=[('http', 'Generic HTTP'), ('gitlab', 'GitLab'), ('github', 'GitHub'), ('bitbucket', 'Bitbucket'), ('gitea', 'Gitea / Forgejo'), ('pypi', 'PyPI / Package Registry'), ('custom', 'Custom Adapter')], default='http', help_text='Target platform adapter used for this sync endpoint.', max_length=50)),
                ('endpoint', models.CharField(blank=True, help_text='Relative API path (HTTP/PyPI) or optional override path for platform APIs.', max_length=255)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Auth settings, e.g. {"token": "...", "token_type": "Bearer"}')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Platform-specific options (org, group_id, workspace, scopes, etc.).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_endpoints', to='userspermissionsystem.appmodule')),
            ],
            options={
                'unique_together': {('app', 'event_type', 'platform_type')},
            },
        ),
    ]
