# Generated by Django 5.1.2 on 2025-07-12 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppURLPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='userspermissionsystem.appmodule')),
            ],
            options={
                'unique_together': {('app', 'url', 'method', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.ManyToManyField(related_name='roles', to='userspermissionsystem.appurlpermission')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.ManyToManyField(blank=True, related_name='users', to='userspermissionsystem.appurlpermission')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='userspermissionsystem.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
