# Generated by Django 5.1.2 on 2025-07-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissionsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodule',
            name='external_api_url',
            field=models.URLField(blank=True, help_text="API endpoint for external module login (used if 'is_external' is True).", null=True),
        ),
        migrations.AddField(
            model_name='appmodule',
            name='icon_file',
            field=models.ImageField(blank=True, null=True, upload_to='module_icons/'),
        ),
        migrations.AddField(
            model_name='appmodule',
            name='icon_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appmodule',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Check this if the module links to an external system or service (e.g., SPYDER).'),
        ),
    ]
