# Generated by Django 5.1.2 on 2025-07-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissionsystem', '0002_appmodule_external_api_url_appmodule_icon_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodule',
            name='url_name',
            field=models.CharField(blank=True, help_text='Django named URL for internal navigation.', max_length=200),
        ),
    ]
