# Generated by Django 5.1.2 on 2025-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissionsystem', '0003_appmodule_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodule',
            name='show_in_home',
            field=models.BooleanField(default=True, help_text='Show this module in the home page menu.'),
        ),
    ]
