# Generated by Django 5.1.2 on 2025-07-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissionsystem', '0004_appmodule_show_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this module currently active?'),
        ),
    ]
