# Generated by Django 4.2.23 on 2025-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissionsystem', '0005_appmodule_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodule',
            name='icon_file',
            field=models.FileField(blank=True, null=True, upload_to='module_icons/'),
        ),
    ]
