# Generated by Django 5.1.2 on 2025-09-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissionsystem', '0007_appmodule_created_at_appmodule_redirect_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSyncEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('create', 'User Create'), ('password', 'Password Change'), ('status', 'Status Change'), ('access', 'Access/Permission Sync')], max_length=50)),
                ('endpoint', models.CharField(help_text='Relative API endpoint, e.g. /api/register/user/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_endpoints', to='userspermissionsystem.appmodule')),
            ],
            options={
                'unique_together': {('app', 'event_type')},
            },
        ),
    ]
