# Generated by Django 5.1.2 on 2025-09-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissionsystem', '0008_externalsyncendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodule',
            name='base_url',
            field=models.URLField(blank=True, help_text='Base URL for this external module’s API (e.g., https://spyder.example.com).', null=True),
        ),
    ]
