# Generated by Django 5.1.2 on 2025-09-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissionsystem', '0009_appmodule_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsyncendpoint',
            name='event_type',
            field=models.CharField(choices=[('create', 'User Create'), ('password', 'Password Change'), ('status', 'Status Change'), ('update', 'User Update'), ('access', 'Access/Permission Sync')], max_length=50),
        ),
    ]
